In [3]:
# numpy INtro 

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(f"Type of arr: {type(arr)}")

[1 2 3 4 5]
Type of arr: <class 'numpy.ndarray'>


In [4]:
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#The array object in NumPy is called ndarray, it provides a lot of supporting functions that 
#make working with ndarray very easy.
#NumPy is usually imported under the np alias.

import numpy

arr = numpy.array([1,2,3,4,5,])

print(arr)

[1 2 3 4 5]


In [5]:
# 1- D Array

import numpy as np

arr = np.array([1,2,3,4,5])

print (arr)


[1 2 3 4 5]


In [6]:
# 2 - D Array

arr = np.array([[1,2,3],[4,5,6]])

print (arr)


[[1 2 3]
 [4 5 6]]


In [7]:
# 3 -D Array 

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print (arr)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
#Check Number of Dimensions?
import numpy as np 

a = np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
#Create an array with 5 dimensions and verify that it has 5 dimensions
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [2]:
#NumPy Array Indexing
#Access Array Elements
#index starts with 0 not 1 the first element of array is [0]
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[1])


2


In [4]:
# 2-D array indexing and accessing 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2 element of the first row :', arr[0,1])
print('3 element of the second row :', arr[1,2])

2 element of the first row : 2
3 element of the second row : 8


In [13]:
# 3-D array indexing and accessing 

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr[0,0,2])
print(arr[0,1,2])
print(arr[0,2,2])

3
6
9


In [15]:
# negative indexing 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print ('Last element from 2nd dim :', arr[1,-1])

Last element from 2nd dim : 10
